### PR TITLE
FIX don't define sum if it's defined by another gem e.g. active_support

### PR DESCRIPTION
**Pull request by gerry3**

### CODE REVIEW

**Comment by brianhempel** [comment]
I find it fascinating that the return classes changed. Thanks for the updates—I will merge this tomorrow.

**Comment by brianhempel** [comment]
I'm opting to coerce `mean` and `median` to always return `Float`s as they did in Ruby 1.8.7. This way, the behavior will be the same between all the Rubies and the README will be telling the truth when it says that `mean` and `median` always return floats. This is stats after all—I'd be surprised if anyone needed more than `Float` precision for their means and medians. Precision is more important for sums, I think.

If you have a practical objection to this, let me know. (Does anyone even use BigDecimal?)

**Comment by gerry3** [comment]
That makes sense to me.

**Comment by brianhempel** [comment]
Okay, I pushed [v1.1.0](http://rubygems.org/gems/simple_stats) to RubyGems.

All methods now accept blocks, like ActiveSupport's sum; though ActiveSupport's sum is preferred.

I also started work on syntactic sugar to make `items.median("cost")` a shorthand for `items.median {|item| item.cost}`. However, I decided it wasn't Ruby-like enough and left it in [a branch](https://github.com/brianhempel/simple_stats/commit/608d83065a760bfec4e2db8f598580c3668bf295).

**Comment by brianhempel** [comment]
Thanks for your help and for alerting me to the conflict.

**Pull request closed without merging**
